### ISSUE TITLE
Compact Solars fails due to mcmod.info having Forge 6.6.1 as reqDep

### ISSUE THREAD

**Issue by fogger** [agaricusb/ModAnalyzer#2]
I can edit the mcmod.info, just thought you might want to know.

**Comment by agaricusb** [comment]
Hm, thought I fixed this with https://github.com/agaricusb/ModAnalyzer/commit/e72c1143ca5b97c8f268e5d0ebf676372701bc55 but will have to double check

**Comment by fogger** [comment]
Hmm, weird, just in case, I re-downloaded the modfixes.py and tried it again & it passed.
