### ISSUE TITLE
Doesn't collect AdvancedMachines.cfg

### ISSUE THREAD

**Issue by fogger** [agaricusb/ModAnalyzer#3]
`/configs/AdvancedMachines_1.5.1.zip/`  is empty, despite there actually being an `AdvancedMachines.cfg` in the temp-server's configs dir.

**Comment by agaricusb** [comment]
Noticed this too, so it's not just me :). Something odd about how this config is initialized..

**Comment by agaricusb** [comment]
Hm, I retested after removing {data,configs}/AdvancedMachines*, and the AdvancedMachines.cfg was generated in configs. Can you retest with latest ModAnalyzer (4590b20714a03901b4945efffc53467503daf4d8), removing temp-server, now runs on Forge 652 - may have somehow fixed this problem..

**Comment by fogger** [comment]
I updated the py scripts from the git, deleted temp-server dir & any mention of AdvancedMachines from configs/data dirs.

It did use Forge 652, but still only created an empty dir in configs.

**Comment by fogger** [comment]
I screen-capped the part in the script where it passed Advanced Machines.  There's a mention of using an ID under 256 for a non world-gen item.

I'm not sure how that could stop you copying the config though..

Well, take a look:
[AdvancedMachines.png](https://dl.dropboxusercontent.com/u/1315574/AdvancedMachines.png)

**Comment by fogger** [comment]
**First Discovery**
I found a way to get the config to save, but only when AdvancedMachines is the only job.
1. Wiped the configs, data & temp-server.
2. Analyzed just IC2, so it would cache Vanilla & IC2.
3. Then added AdvancedMachines to allmods and analyzed again.

This is the ONLY way it will save the config file.

If you start fresh with just IC2 & AdvancedMachines in allmods, this is what happens:
- Analyze Vanilla, copy forge cfg's
- Analyze AdvancedMachines, **No @ symbol copy/ignore messages at all**
- Analyze IC2, copy ic2.cfg, ignore Vanilla cfg's

**Second Discovery**
It occurred to me that AdvancedMachines was the first mod in my pack (alphabetically), so I prefixed the filename with `z_` and instead of analyzing it before IC2, it came after, and the cfg was saved.

At first I thought it might be a bug with the first mod in the job after Vanilla, but IC2's cfg was copied no problem when it was first.

**Comment by fogger** [comment]
Yep, as long as it's analyzed after IC2, by renaming it so it is alphabetically after IC2, then it saves the config.

`kAdvancedMachines` works
`hAdvancedMachines` doesn't 

Maybe it is relying on a previously saved ic2.cfg?

Not sure if relevant, but this error appears both times. The block in question is given id 4096 in the end:

```
[WARNING] [ForgeModLoader] Mod attempted to get a block ID with a default in the Terrain Generation section, mod authors should make sure there defaults are above 256 unless explicitly needed for terrain generation. Most ores do not need to be below 256.
[WARNING] [ForgeModLoader] Config "/config/AdvancedMachines.cfg" Category: "IDs" Key: "AdvancedMachineBlock" Default: 188
```
