### ISSUE TITLE
Infinite loop with MineFactoryReloaded

### ISSUE THREAD

**Issue by fogger** [agaricusb/ModAnalyzer#7]
When the script reaches MFR, it correctly fetches the PowerCrystalsCore, starts the server, shows the correct output, terminates the server normally, and then repeats the process with MFR & PCC forever.

and all along, nothing for either MFR or PCC is ever created in configs/data.

**allmods**
`PowerCrystalsCore-1.1.1-75.jar`
`MineFactoryReloaded-2.4.1B1-482.jar`

temp-server: [ForgeModLoader-server-0.log](https://dl.dropboxusercontent.com/u/1315574/ForgeModLoader-server-0.log)

**Comment by agaricusb** [comment]
Circular dependency - MFR 'depends' on itself, because it has submods in the same mcmod.info, which I merge together..
